<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.1" />

    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <xacro:property name="camera_length" value="0.05" />
    <xacro:property name="camera_width" value="0.3" />
    <xacro:property name="camera_height" value="0.1" />

    <xacro:property name="lidar_radius" value="0.05" />
    <xacro:property name="lidar_length" value="0.025" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}" 
                            xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${2*wheel_radius}" h="${2*wheel_length}" 
                                xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right_front" />
    <xacro:wheel_link prefix="left_front" />
    <xacro:wheel_link prefix="right_back" />
    <xacro:wheel_link prefix="left_back" />

    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="yellow" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${2*lidar_radius}" h="${2*lidar_length}" 
                            xyz="0 0 0" rpy="0 0 0" />
    </link>

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" /> 
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" /> 
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="0.1" l="${camera_length}" w="${camera_width}" h="${camera_height}" 
                            xyz="0 0 0" rpy="0 0 0" />
    </link>

    <link name="camera_link_optical" />

    <link name="base_footprint" />

    <joint name="base_right_front_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_front_wheel_link" />
        <origin xyz="${base_length / 3.0} ${(-base_width / 2.0) - (wheel_length / 2.0)} ${base_height / 2.0}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_front_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_front_wheel_link" />
        <origin xyz="${base_length / 3.0} ${(base_width / 2.0) + (wheel_length / 2.0)} ${base_height / 2.0}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_right_back_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_back_wheel_link" />
        <origin xyz="${-base_length / 3.0} ${(-base_width / 2.0) - (wheel_length / 2.0)} ${base_height / 2.0}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_back_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_back_wheel_link" />
        <origin xyz="${-base_length / 3.0} ${(base_width / 2.0) + (wheel_length / 2.0)} ${base_height / 2.0}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_link" />
        <origin xyz="${(base_length / 2.0) - (camera_length / 2.0)} 0 ${(base_height / 2.0 + camera_height)}" rpy="0 0 0" />
    </joint>

    <joint name="camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
    </joint>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar_link" />
        <origin xyz="${base_length / 2.0} 0 ${base_height / 2.0}" rpy="0 0 0" />
        <axis xyz="0 0 0" />
    </joint>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius - (base_height / 2.0)}" rpy="0 0 0" />
    </joint>

</robot>